[build]
  command = "echo '--- ETAPE 1 prisma generate ---' && npx prisma generate && echo '--- ETAPE 2 prisma db push ---' && npx prisma db push --accept-data-loss --skip-generate && echo '--- ETAPE 3 seed ---' && npx tsx prisma/seed.ts && echo '--- ETAPE 4 next build ---' && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
